apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: user-namespace
spec:
  containers:
  - name: test-container
    image: my-registry/my-base-image:latest
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-volume
  volumes:
  - name: shared-volume
    emptyDir: {}